# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - demotestgroupA

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_60497f851e8543f68db5824dde0c8868 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_53c69e3584dc4052943ee0d603c695b5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_60497f851e8543f68db5824dde0c8868 }}/gpa_w12:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'demotestgroupA'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6b7c4d22dddb4ddfaf2a4e7c0c18cb88 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_60497f851e8543f68db5824dde0c8868 }}/gpa_w12:${{ github.sha }}'